In [1]:
!pip install opendatasets --upgrade --quiet

In [ ]:
import opendatasets as od

In [ ]:
od.version()

'0.1.22'

In [ ]:
dataset_url = 'https://www.kaggle.com/datasets/lakshmi25npathi/imdb-dataset-of-50k-movie-reviews'

In [ ]:
od.download(dataset_url)

Dataset URL: https://www.kaggle.com/datasets/lakshmi25npathi/imdb-dataset-of-50k-movie-reviews


100%|██████████| 25.7M/25.7M [00:00<00:00, 194MB/s]

In [ ]:
import os

In [ ]:
data_dir_name = './imdb-dataset-of-50k-movie-reviews'

In [ ]:
os.listdir(data_dir_name)

['IMDB Dataset.csv']

In [ ]:
data_csv = data_dir_name + '/IMDB Dataset.csv'

In [ ]:
data_csv

'./imdb-dataset-of-50k-movie-reviews/IMDB Dataset.csv'

In [ ]:
import pandas as pd

In [ ]:
raw_df = pd.read_csv(data_csv)

In [ ]:
raw_df

review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
nltk.download('punkt_tab')
import string
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn .metrics import confusion_matrix
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', 255)


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


In [ ]:
raw_df.shape

(50000, 2)

In [ ]:
df =raw_df.iloc[:10000]

In [ ]:
df.head()

review  \
0  One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of v...   
1  A wonderful little production. <br /><br />The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. <br /><br />The actors are extremely well chosen-...   
2  I thought this was a wonderful way to spend time on a too hot summer weekend, sitting in the air conditioned theater and watching a light-hearted comedy. The plot is simplistic, but the dialogue is witty and the characters are likable (even the well b...   
3  Basically there's a family where a little boy (Jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />This movie is slower than a soap opera... and suddenly, Jake decides to become Rambo and kill the zombie.<br...   
4  Petter Mattei's "Love in the Time of Money" is a visually stunning film to watch. Mr. Mattei offers us a vivid portrait about human relations. This is a movie that seems to be telling us what money, power and success do to people in the different situ...   

  sentiment  
0  positive  
1  positive  
2  positive  
3  negative  
4  positive

In [ ]:
df.shape

(10000, 2)

In [ ]:
df['sentiment'].value_counts()

sentiment
positive    5028
negative    4972
Name: count, dtype: int64

In [ ]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [ ]:
df.duplicated().sum()

17

In [ ]:
df.drop_duplicates(inplace=True)

<ipython-input-22-16cdb8520be8>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop_duplicates(inplace=True)


In [ ]:
df.duplicated().sum()

0

# Basic Preprocessing


*   Remove tags -HTML
*   Lower case


*   remove stopwords





In [ ]:
import re
def remove_html_tag(raw_text):
  pattern = re.compile('<.*?>')
  return pattern.sub(r'',raw_text)

In [ ]:
df['review'] = df['review'].apply(remove_html_tag)

<ipython-input-25-1c542e3b05dd>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].apply(remove_html_tag)


In [ ]:
df['review'][0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.I would say the main appeal of the show is due to the fact that it goes where other shows wo

In [ ]:
df['review'] = df['review'].apply(lambda x:x.lower())

<ipython-input-27-afca29351ee0>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].apply(lambda x:x.lower())


In [ ]:
df['review'][0]

"one of the other reviewers has mentioned that after watching just 1 oz episode you'll be hooked. they are right, as this is exactly what happened with me.the first thing that struck me about oz was its brutality and unflinching scenes of violence, which set in right from the word go. trust me, this is not a show for the faint hearted or timid. this show pulls no punches with regards to drugs, sex or violence. its is hardcore, in the classic use of the word.it is called oz as that is the nickname given to the oswald maximum security state penitentary. it focuses mainly on emerald city, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. em city is home to many..aryans, muslims, gangstas, latinos, christians, italians, irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.i would say the main appeal of the show is due to the fact that it goes where other shows wo

In [ ]:
from nltk.corpus import stopwords
import nltk
nltk.download('stopwords')
sw_list = stopwords.words('english')
df['review'] = df['review'].apply(lambda x:[item for item in x.split() if item not in sw_list]).apply(lambda x:' '.join(x))

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
<ipython-input-29-108377f0870a>:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].apply(lambda x:[item for item in x.split() if item not in sw_list]).apply(lambda x:' '.join(x))


In [ ]:
df['review'][0]

"one reviewers mentioned watching 1 oz episode hooked. right, exactly happened me.the first thing struck oz brutality unflinching scenes violence, set right word go. trust me, show faint hearted timid. show pulls punches regards drugs, sex violence. hardcore, classic use word.it called oz nickname given oswald maximum security state penitentary. focuses mainly emerald city, experimental section prison cells glass fronts face inwards, privacy high agenda. em city home many..aryans, muslims, gangstas, latinos, christians, italians, irish more....so scuffles, death stares, dodgy dealings shady agreements never far away.i would say main appeal show due fact goes shows dare. forget pretty pictures painted mainstream audiences, forget charm, forget romance...oz mess around. first episode ever saw struck nasty surreal, say ready it, watched more, developed taste oz, got accustomed high levels graphic violence. violence, injustice (crooked guards who'll sold nickel, inmates who'll kill order g

In [ ]:
x = df.iloc[:,0:1]
y = df['sentiment']

In [ ]:
x.head()

review
0  one reviewers mentioned watching 1 oz episode hooked. right, exactly happened me.the first thing struck oz brutality unflinching scenes violence, set right word go. trust me, show faint hearted timid. show pulls punches regards drugs, sex violence. ha...
1  wonderful little production. filming technique unassuming- old-time-bbc fashion gives comforting, sometimes discomforting, sense realism entire piece. actors extremely well chosen- michael sheen "has got polari" voices pat too! truly see seamless edit...
2  thought wonderful way spend time hot summer weekend, sitting air conditioned theater watching light-hearted comedy. plot simplistic, dialogue witty characters likable (even well bread suspected serial killer). may disappointed realize match point 2: r...
3  basically there's family little boy (jake) thinks there's zombie closet & parents fighting time.this movie slower soap opera... suddenly, jake decides become rambo kill zombie.ok, first going make film must decide thriller drama! drama movie watchable...
4  petter mattei's "love time money" visually stunning film watch. mr. mattei offers us vivid portrait human relations. movie seems telling us money, power success people different situations encounter. variation arthur schnitzler's play theme, director ...

In [ ]:
y.head()

0    positive
1    positive
2    positive
3    negative
4    positive
Name: sentiment, dtype: object

In [ ]:
y.shape

(9983,)

In [ ]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
y = encoder.fit_transform(y)

In [ ]:
y

array([1, 1, 1, ..., 0, 0, 1])

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=1)

In [ ]:
x_train.shape

(7986, 1)

In [ ]:
y_train.shape

(7986,)

# Applying **BOW**

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
x_train_bow = cv.fit_transform(x_train['review']).toarray()
x_test_bow = cv.transform(x_test['review']).toarray()

In [ ]:
x_train_bow

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(x_train_bow,y_train)

GaussianNB()

In [ ]:
y_pred = gnb.predict(x_test_bow)

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix
accuracy_score(y_test,y_pred)

0.6324486730095142

In [ ]:
confusion_matrix(y_test,y_pred)

array([[717, 235],
       [499, 546]])

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(x_train_bow,y_train)
y_pred = rf.predict(x_test_bow)
accuracy_score(y_test,y_pred)

0.8517776664997496

In [ ]:
cv = CountVectorizer(max_features=3000)
x_train_bow = cv.fit_transform(x_train['review']).toarray()
x_test_bow = cv.transform(x_test['review']).toarray()
rf = RandomForestClassifier()
rf.fit(x_train_bow,y_train)
y_pred = rf.predict(x_test_bow)
accuracy_score(y_test,y_pred)

0.8407611417125689

# N gram

In [ ]:
cv = CountVectorizer(ngram_range=(2,2),max_features=5000)
x_train_bow = cv.fit_transform(x_train['review']).toarray()
x_test_bow = cv.transform(x_test['review']).toarray()
rf = RandomForestClassifier()
rf.fit(x_train_bow,y_train)
y_pred = rf.predict(x_test_bow)
accuracy_score(y_test,y_pred)

0.7536304456685028

# TFIDF

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()
x_train_tfidf = tfidf.fit_transform(x_train['review']).toarray()
x_test_tfidf = tfidf.transform(x_test['review']).toarray()
rc = RandomForestClassifier()
rc.fit(x_train_tfidf,y_train)
y_pred = rc.predict(x_test_tfidf)
accuracy_score(y_test,y_pred)

0.8477716574862293

# Word2Vec

In [ ]:
from nltk.tokenize import word_tokenize
from sklearn.ensemble import RandomForestClassifier
from gensim.models import Word2Vec
import gensim


In [ ]:
raw_df

Output hidden; open in https://colab.research.google.com to view.

In [ ]:
raw_df.shape

(50000, 2)

In [ ]:
df['target'] = df['sentiment'].apply(lambda x:1 if x=='positive' else 0)

<ipython-input-53-20215dab4fcb>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['target'] = df['sentiment'].apply(lambda x:1 if x=='positive' else 0)


In [ ]:
df['target']

0       1
1       1
2       1
3       0
4       1
5       1
6       1
7       0
8       0
9       1
10      0
11      0
12      0
13      0
14      1
15      0
16      1
17      0
18      1
19      0
20      1
21      0
22      1
23      0
24      0
25      1
26      1
27      0
28      0
29      1
30      1
31      1
32      0
33      1
34      0
35      0
36      0
37      0
38      1
39      0
40      0
41      1
42      0
43      0
44      1
45      1
46      0
47      0
48      1
49      0
50      1
51      1
52      1
53      1
54      0
55      0
56      0
57      0
58      1
59      1
60      0
61      0
62      1
63      0
64      0
65      1
66      0
67      0
68      0
69      0
70      0
71      0
72      1
73      1
74      0
75      1
76      1
77      0
78      0
79      1
80      1
81      0
82      0
83      0
84      0
85      0
86      0
87      0
88      0
89      0
90      1
91      0
92      1
93      1
94      0
95      1
96      0
97      0
98      0
99      1
100     1
101     0
102     1
103     1
104     0
105     1
106     1
107     0
108     1
109     1
110     0
111     0
112     0
113     1
114     1
115     1
116     1
117     0
118     0
119     0
120     1
121     1
122     0
123     0
124     1
125     0
126     0
127     0
128     1
129     1
130     1
131     1
132     0
133     0
134     0
135     0
136     1
137     0
138     1
139     0
140     0
141     0
142     0
143     1
144     0
145     1
146     1
147     1
148     0
149     0
150     1
151     0
152     0
153     1
154     0
155     0
156     0
157     1
158     0
159     1
160     1
161     0
162     0
163     0
164     1
165     0
166     1
167     0
168     0
169     0
170     0
171     0
172     1
173     1
174     0
175     0
176     1
177     0
178     1
179     0
180     1
181     0
182     0
183     0
184     0
185     0
186     1
187     0
188     1
189     0
190     1
191     1
192     1
193     1
194     0
195     0
196     0
197     0
198     1
199     0
200     0
201     1
202     1
203     1
204     0
205     1
206     0
207     0
208     1
209     1
210     0
211     0
212     0
213     1
214     0
215     1
216     1
217     0
218     1
219     0
220     0
221     1
222     1
223     0
224     1
225     0
226     1
227     1
228     1
229     1
230     0
231     1
232     1
233     1
234     1
235     1
236     1
237     0
238     1
239     0
240     0
241     1
242     0
243     1
244     0
245     1
246     0
247     0
248     1
249     0
250     0
251     0
252     0
253     0
254     1
255     0
256     0
257     0
258     1
259     1
260     1
261     0
262     0
263     0
264     0
265     1
266     0
267     0
268     0
269     1
270     0
271     1
272     1
273     1
274     0
275     1
276     0
277     1
278     0
279     1
280     1
281     0
282     0
283     0
284     1
285     0
286     1
287     1
288     1
289     1
290     1
291     1
292     1
293     1
294     1
295     0
296     0
297     1
298     1
299     1
300     0
301     0
302     1
303     1
304     1
305     1
306     1
307     0
308     0
309     0
310     1
311     0
312     0
313     0
314     0
315     0
316     1
317     1
318     1
319     0
320     1
321     1
322     0
323     1
324     0
325     1
326     1
327     0
328     1
329     1
330     0
331     1
332     1
333     1
334     1
335     0
336     1
337     1
338     0
339     0
340     0
341     1
342     0
343     1
344     0
345     0
346     0
347     1
348     0
349     0
350     1
351     0
352     0
353     1
354     0
355     0
356     1
357     0
358     0
359     0
360     1
361     0
362     1
363     1
364     1
365     0
366     0
367     0
368     1
369     1
370     1
371     1
372     0
373     1
374     1
375     0
376     1
377     0
378     1
379     0
380     0
381     1
382     1
383     0
384     0
385     0
386     0
387     1
388     1
389     1
390     1
391     0
392     1
393     1
394     1
395     0
396     0
397     1
398     0
399     1


In [ ]:
df['target'].shape

(9983,)

In [ ]:
df['review'].shape

(9983,)

In [ ]:
def preprocess_text(text):
  text = re.sub(r"[^a-zA-Z]", " ", text.lower())
  tokens = word_tokenize(text)
  return tokens

In [ ]:
df['tokens'] = df['review'].apply(preprocess_text)

<ipython-input-61-cd8e05ca4703>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['tokens'] = df['review'].apply(preprocess_text)


In [ ]:
df['tokens']

Output hidden; open in https://colab.research.google.com to view.

In [ ]:
w2v_model = Word2Vec(sentences=df['tokens'],vector_size=100,window=5,min_count=2,workers=4)

In [ ]:
def get_vector(text_tokens, model):
  vectors = [model.wv[word] for word in text_tokens if word in model.wv]
  if vectors:
    return np.mean(vectors, axis=0)
  else:
    return np.zeros(model.vector_size)

In [ ]:
df['vector'] = df['tokens'].apply(lambda x: get_vector(x, w2v_model))

<ipython-input-68-7562ce0f6609>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['vector'] = df['tokens'].apply(lambda x: get_vector(x, w2v_model))


In [ ]:
df['vector']

Output hidden; open in https://colab.research.google.com to view.

# Train the RandomForestClassifier

In [ ]:
x = np.vstack(df['vector'].values)
y = df['target'].values

In [ ]:
x

array([[-0.12507181,  0.36592487,  0.18832488, ..., -0.0904208 ,
         0.13225338,  0.086744  ],
       [-0.2053786 ,  0.41518444,  0.2139387 , ..., -0.32791352,
         0.1928234 ,  0.18646117],
       [-0.1597765 ,  0.34448332,  0.14967448, ..., -0.21076241,
         0.21064754,  0.15522945],
       ...,
       [-0.28835142,  0.45482594,  0.07927453, ..., -0.17364322,
         0.19285893, -0.05029063],
       [-0.31156126,  0.5918881 ,  0.22943811, ..., -0.03359657,
         0.4065767 , -0.07126802],
       [-0.21339422,  0.27152932,  0.21529113, ..., -0.42105764,
         0.23684329,  0.11105771]], dtype=float32)

In [ ]:
y

array([1, 1, 1, ..., 0, 0, 1])

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
x_train.shape

(7986, 100)

In [ ]:
clf = RandomForestClassifier()
clf.fit(x_train,y_train)

RandomForestClassifier()

In [ ]:
y_pred = clf.predict(x_test)

In [ ]:
y_pred

array([0, 0, 1, ..., 1, 0, 0])

In [ ]:
conf_matrix = confusion_matrix(y_test,y_pred)
print("Confution Matrix:\n", conf_matrix)

Confution Matrix:
 [[773 212]
 [213 799]]


In [ ]:
accuracy_score(y_test,y_pred)

0.7871807711567351